library(usethis)
library(roxygen2)
library(devtools)

use_git_config(user.name = "urswilke", user.email = "urs.wilke@gmail.com")
use_git()
use_readme_rmd()
usethis::use_mit_license("Urs Wilke")
use_testthat()
use_vignette("scrape_thread")
use_package("rtweet")
use_package("dplyr")
use_package("stringr")
use_package("purrr")
use_pipe()
devtools::install()
devtools::check()
use_r("scraping")
