#' Recursively return all status ids of a tweet and its replies
#'
#' @param df_tree data frame returned by `rtweet::search_tweets2()`.
#' @param df0 data frame returned by `rtweet::lookup_statuses()`.
#'
#' @return Edges data frame that can be plotted by tidygraph & ggraph
#'
#' @examples
#' main_status_id <- "1438481824922181635"
#'\dontrun{
#' df_main_status <- rtweet::lookup_statuses(main_status_id)
#' df_tree <- search_tree(main_status_id)
#' tree_ids <- df_tree$user_id %>% unique()
#' df_tls <- scrape_timelines(tree_ids)
#'df0 <- df_main_status %>%
#'                        dplyr::filter(status_id == main_status_id) %>%
#'                        dplyr::select(to = status_id, user_id) %>%
#'                        dplyr::mutate(from = "root", type = "root")
#' tweet_edges <-
#' find_connections_rec(dplyr::bind_rows(df_tree, df_tls), df0)
#' }
find_connections_rec <- function(df_tree, df0) {
  df_quote1 <-
    df_tree %>%
    dplyr::filter(.data$quoted_status_id %in% df0$to) %>%
    dplyr::select(to = .data$status_id, from = .data$quoted_status_id, .data$user_id, .data$screen_name) %>%
    dplyr::mutate(type = "quote")
  df_reply1 <-
    df_tree %>%
    dplyr::filter(.data$reply_to_status_id %in% df0$to) %>%
    dplyr::select(to = .data$status_id, from = .data$reply_to_status_id, .data$user_id, .data$screen_name) %>%
    dplyr::mutate(type = "reply")
  res <- list(df0, df_reply1, df_quote1) %>%
    purrr::reduce(dplyr::full_join) %>%
    dplyr::distinct()
  if (nrow(res) == nrow(df0)) {
    return(res)
  } else {
    find_connections_rec(df_tree, res)
  }
}


#' Create ggraph object with profile pictures added
#'
#' @param g1 tbl_graph object
#' @param df_profile_pic tibble of profile pictures, generated by `scrape_profile_pics()` (see examples).
#'
#' @return ggraph object of tweet tree with profile pictures
#' @export
#'
#' @examples
#' \dontrun{
#' l <- rtweettree_data("1438481824922181635")
#' g <- rtweettree_tbl_graph(l)
#' g1 <- ggraph(g)
#' g1 <- add_profile_pics_to_tree_ggraph(g1, rtweettree:::scrape_profile_pics(tidygraph::as_tibble(g)))
#' g1 + ggraph::geom_edge_diagonal(aes(color= type)) + geom_node_point(aes(shape = type))
#' }
add_profile_pics_to_tree_ggraph <- function(g1, df_profile_pic) {

  # Hack to put all user nodes on the bottom line of the graph:
  g1$data$y[g1$data$type == "user"] <- min(g1$data$y)

  user_coords <- g1$data %>%
    dplyr::filter(.data$type == "user") %>%
    dplyr::select(.data$screen_name, .data$x, .data$y)

  df_profile_pic <- df_profile_pic %>% dplyr::inner_join(user_coords, by = "screen_name")
  user_coords <- df_profile_pic %>% dplyr::select(.data$screen_name, .data$x, .data$y)
  add_img <- function(g1, user_images, user_coords) {
    # TODO: allow to choose the width & height parameters from the calling function:
    g1  + ggplot2::annotation_raster(user_images, xmin = user_coords$x[1] - 0.4, ymin = user_coords$y[1] + 0.2, xmax = user_coords$x[1] + 0.4, ymax = user_coords$y[1] + 0.6)
  }
  purrr::reduce2(
    df_profile_pic$profile_pic,
    user_coords %>% dplyr::rowwise() %>% dplyr::group_split(),
    add_img,
    .init = g1
  )
}
