#' Create an empty rtweet tibble
#'
#'
#' @return An empty tibble with columns of the type that, e.g. rtweet::lookup_statuses() produces
#'
#' @examples
#' df <- create_empty_rtweet_tbl()
#' df
create_empty_rtweet_tbl <- function() {
  tibble::tibble(
    user_id = character(0),
    status_id = character(0),
    created_at = structure(
      numeric(0),
      tzone = "UTC",
      class = c("POSIXct",
                "POSIXt")
    ),
    screen_name = character(0),
    text = character(0),
    source = character(0),
    display_text_width = numeric(0),
    reply_to_status_id = character(0),
    reply_to_user_id = character(0),
    reply_to_screen_name = character(0),
    is_quote = logical(0),
    is_retweet = logical(0),
    favorite_count = integer(0),
    retweet_count = integer(0),
    quote_count = integer(0),
    reply_count = integer(0),
    hashtags = list(),
    symbols = list(),
    urls_url = list(),
    urls_t.co = list(),
    urls_expanded_url = list(),
    media_url = list(),
    media_t.co = list(),
    media_expanded_url = list(),
    media_type = list(),
    ext_media_url = list(),
    ext_media_t.co = list(),
    ext_media_expanded_url = list(),
    ext_media_type = character(0),
    mentions_user_id = list(),
    mentions_screen_name = list(),
    lang = character(0),
    quoted_status_id = character(0),
    quoted_text = character(0),
    quoted_created_at = structure(
      numeric(0),
      tzone = "UTC",
      class = c("POSIXct",
                "POSIXt")
    ),
    quoted_source = character(0),
    quoted_favorite_count = integer(0),
    quoted_retweet_count = integer(0),
    quoted_user_id = character(0),
    quoted_screen_name = character(0),
    quoted_name = character(0),
    quoted_followers_count = integer(0),
    quoted_friends_count = integer(0),
    quoted_statuses_count = integer(0),
    quoted_location = character(0),
    quoted_description = character(0),
    quoted_verified = logical(0),
    retweet_status_id = character(0),
    retweet_text = character(0),
    retweet_created_at = structure(
      numeric(0),
      tzone = "UTC",
      class = c("POSIXct",
                "POSIXt")
    ),
    retweet_source = character(0),
    retweet_favorite_count = integer(0),
    retweet_retweet_count = integer(0),
    retweet_user_id = character(0),
    retweet_screen_name = character(0),
    retweet_name = character(0),
    retweet_followers_count = integer(0),
    retweet_friends_count = integer(0),
    retweet_statuses_count = integer(0),
    retweet_location = character(0),
    retweet_description = character(0),
    retweet_verified = logical(0),
    place_url = character(0),
    place_name = character(0),
    place_full_name = character(0),
    place_type = character(0),
    country = character(0),
    country_code = character(0),
    geo_coords = list(),
    coords_coords = list(),
    bbox_coords = list(),
    status_url = character(0),
    name = character(0),
    location = character(0),
    description = character(0),
    url = character(0),
    protected = logical(0),
    followers_count = integer(0),
    friends_count = integer(0),
    listed_count = integer(0),
    statuses_count = integer(0),
    favourites_count = integer(0),
    account_created_at = structure(
      numeric(0),
      tzone = "UTC",
      class = c("POSIXct",
                "POSIXt")
    ),
    verified = logical(0),
    profile_url = character(0),
    profile_expanded_url = character(0),
    account_lang = logical(0),
    profile_banner_url = character(0),
    profile_background_url = character(0),
    profile_image_url = character(0)
  )
}
